/**
 * Generates `supabase/migrations/0002_seed.sql` from the TypeScript content
 * catalogues.
 *
 * The server has to know lesson payouts and the duel answer key, but that data
 * already lives in `src/content`. Generating the SQL keeps one source of truth —
 * re-run this after changing rewards, shop items or the quickfire bank.
 *
 *   node scripts/generate-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Pulls literal values out of a TS source file without needing a compiler. */
function read(file) {
  return readFileSync(join(root, 'src/content', file), 'utf8');
}

const sq = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (items) => `array[${items.map(sq).join(', ')}]`;

// --- rewards (lessons + projects) ---
const lessonsSrc = read('lessons.ts');
const lessonRows = [
  ...lessonsSrc.matchAll(/id:\s*'([^']+)',[\s\S]*?rewardPi:\s*(\d+),\s*rewardXp:\s*(\d+)/g),
].map((m) => ({ kind: 'lesson', id: m[1], pi: Number(m[2]), xp: Number(m[3]) }));

const projectsSrc = read('projects.ts');
const projectRows = [
  ...projectsSrc.matchAll(/id:\s*'([^']+)',[\s\S]*?rewardPi:\s*(\d+),\s*rewardXp:\s*(\d+)/g),
].map((m) => ({ kind: 'project', id: m[1], pi: Number(m[2]), xp: Number(m[3]) }));

// --- shop items ---
const shopSrc = read('shop.ts');
const shopRows = [...shopSrc.matchAll(/\{\s*id:\s*'([^']+)',[\s\S]*?\n\s*\},/g)].map((m) => {
  const block = m[0];
  const pick = (re) => block.match(re)?.[1];
  return {
    id: m[1],
    cost: Number(pick(/cost:\s*(\d+)/)),
    kind: pick(/kind:\s*'([^']+)'/),
    keyId: pick(/keyId:\s*'([^']+)'/) ?? null,
  };
});

// --- quickfire bank (with the answer key) ---
const qfSrc = read('quickfire.ts');
const qfRows = [
  ...qfSrc.matchAll(
    /\{\s*\n?\s*equation:\s*'([^']*)',\s*\n?\s*prompt:\s*'([^']*)',\s*\n?\s*options:\s*\[([^\]]*)\],\s*\n?\s*correctIndex:\s*(\d+)/g,
  ),
].map((m, i) => ({
  id: i + 1,
  equation: m[1],
  prompt: m[2],
  options: [...m[3].matchAll(/'([^']*)'/g)].map((o) => o[1]),
  correctIndex: Number(m[4]),
}));

if (lessonRows.length === 0 || qfRows.length === 0 || shopRows.length === 0) {
  console.error('Parsed nothing — the content files may have changed shape.');
  process.exit(1);
}

const sql = `-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Mirrors src/content so the server can grant rewards and grade duels.

insert into public.rewards (kind, item_id, reward_pi, reward_xp) values
${[...lessonRows, ...projectRows]
  .map((r) => `  (${sq(r.kind)}, ${sq(r.id)}, ${r.pi}, ${r.xp})`)
  .join(',\n')}
on conflict (kind, item_id) do update
  set reward_pi = excluded.reward_pi, reward_xp = excluded.reward_xp;

insert into public.shop_items (id, cost, kind, key_id) values
${shopRows
  .map((r) => `  (${sq(r.id)}, ${r.cost}, ${sq(r.kind)}, ${r.keyId ? sq(r.keyId) : 'null'})`)
  .join(',\n')}
on conflict (id) do update
  set cost = excluded.cost, kind = excluded.kind, key_id = excluded.key_id;

insert into public.quickfire (id, equation, prompt, options, correct_index) values
${qfRows
  .map(
    (q) => `  (${q.id}, ${sq(q.equation)}, ${sq(q.prompt)}, ${arr(q.options)}, ${q.correctIndex})`,
  )
  .join(',\n')}
on conflict (id) do update
  set equation = excluded.equation, prompt = excluded.prompt,
      options = excluded.options, correct_index = excluded.correct_index;
`;

writeFileSync(join(root, 'supabase/migrations/0002_seed.sql'), sql);
console.log(
  `Wrote 0002_seed.sql — ${lessonRows.length} lessons, ${projectRows.length} projects, ` +
    `${shopRows.length} shop items, ${qfRows.length} questions.`,
);
