-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Mirrors src/content so the server can grant rewards and grade duels.

insert into public.rewards (kind, item_id, reward_pi, reward_xp) values
  ('lesson', 'why', 20, 30),
  ('lesson', 'problem-basics', 25, 40),
  ('lesson', 'coefficients-abc', 25, 40),
  ('lesson', 'no-b-basics', 30, 50),
  ('lesson', 'no-c-basics', 30, 50),
  ('lesson', 'full-discriminant', 40, 70),
  ('lesson', 'vieta-intro', 40, 70),
  ('lesson', 'beat-the-clock-1', 60, 100),
  ('project', 'rescue-flare', 120, 200)
on conflict (kind, item_id) do update
  set reward_pi = excluded.reward_pi, reward_xp = excluded.reward_xp;

insert into public.shop_items (id, cost, kind, key_id) values
  ('avatar-comet', 100, 'avatar', null),
  ('avatar-saturn', 250, 'avatar', null),
  ('collectable-galaxy', 500, 'collectable', null),
  ('consumable-fortune-cookie', 50, 'consumable', null),
  ('key-sqrt', 150, 'key', 'sqrt'),
  ('key-pm', 150, 'key', 'pm'),
  ('key-divide', 120, 'key', 'divide'),
  ('key-y', 200, 'key', 'var-y')
on conflict (id) do update
  set cost = excluded.cost, kind = excluded.kind, key_id = excluded.key_id;

insert into public.quickfire (id, equation, prompt, options, correct_index) values
  (1, '3x² + 5x − 2 = 0', 'a =', array['3', '5', '−2'], 0),
  (2, '3x² + 5x − 2 = 0', 'b =', array['3', '5', '−2'], 1),
  (3, '3x² + 5x − 2 = 0', 'c =', array['3', '5', '−2'], 2),
  (4, 'x² − 7 = 0', 'b =', array['1', '0', '−7'], 1),
  (5, '4x² + x = 0', 'c =', array['0', '1', '4'], 0),
  (6, 'x² = 25', 'x =', array['±5', '5', '±25'], 0),
  (7, 'x² = 49', 'x =', array['7', '±7', '±49'], 1),
  (8, 'x(x − 4) = 0', 'roots', array['0 and 4', '4 only', '−4 and 0'], 0),
  (9, 'x(x + 3) = 0', 'roots', array['0 and 3', '0 and −3', '3 only'], 1),
  (10, 'x² − 4x + 4 = 0', 'D =', array['0', '16', '32'], 0),
  (11, 'x² + 2x + 5 = 0', 'D =', array['−16', '24', '16'], 0),
  (12, 'x² − 5x + 6 = 0', 'D =', array['1', '49', '−1'], 0),
  (13, 'x² − 5x + 6 = 0', 'sum of roots', array['5', '−5', '6'], 0),
  (14, 'x² − 5x + 6 = 0', 'product of roots', array['5', '6', '−6'], 1),
  (15, 'x² + 3x − 10 = 0', 'product of roots', array['−10', '10', '3'], 0),
  (16, 'D < 0', 'how many roots?', array['0', '1', '2'], 0),
  (17, 'D = 0', 'how many roots?', array['0', '1', '2'], 1),
  (18, 'D > 0', 'how many roots?', array['0', '1', '2'], 2)
on conflict (id) do update
  set equation = excluded.equation, prompt = excluded.prompt,
      options = excluded.options, correct_index = excluded.correct_index;
